Starting test:LL131
Running LL131 on Chrome
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> OpenQA.Selenium.NoSuchElementException: The element could not be found
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByLinkText(String linkText)
   at OpenQA.Selenium.By.<>c__DisplayClass6.<LinkText>b__4(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at SeleniumTests.LL131.TheLL131Test() in c:\SeleniumHarness\code\SeleniumHarness\SeleniumHarness\Tests\LL_131.cs:line 119
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at CallSite.Target(Closure , CallSite , MethodInfo , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at SeleniumHarness.TestRunner.executeInBrowser(Browser browser) in c:\SeleniumHarness\code\SeleniumHarness\SeleniumHarness\TestRunner.cs:line 57
test: LL131 is broken on Chrome
Finished test:LL131 on Chrome
Running LL131 on Safari
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Yikes! Safari history navigation does not work. We can go forward or back, but once we do, we can no longer communicate with the page...
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteNavigator.Back()
   at SeleniumTests.LL131.TheLL131Test() in c:\SeleniumHarness\code\SeleniumHarness\SeleniumHarness\Tests\LL_131.cs:line 93
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at CallSite.Target(Closure , CallSite , MethodInfo , Object , Object )
   at SeleniumHarness.TestRunner.executeInBrowser(Browser browser) in c:\SeleniumHarness\code\SeleniumHarness\SeleniumHarness\TestRunner.cs:line 57
test: LL131 is broken on Safari
Finished test:LL131 on Safari
Running LL131 on IE
